### ISSUE TITLE
Running tiny-zoom using docker generates error .  Validated locally and on Digital Ocean

### ISSUE THREAD

**Issue by cloudguru-bb** [dsilabs/docker-zoom-tiny#1] opened 2017-04-21 20:49 UTC
Hi,

The following error was validated locally on OSX and on Ubuntu 16.04 in Digital Ocean while executing tiny-zoom with the instructions provided in the README . The results are displayed in the browser when attempting to connect after validating the docker image is running with -p 8080:8080 as expected.

Traceback (most recent call last):
  File "/tmp/zoom/zoom/middleware.py", line 265, in capture_stdout
    result = handler(request, *rest)
  File "/tmp/zoom/zoom/site.py", line 134, in site_handler
    request.site = Site(request)
  File "/tmp/zoom/zoom/site.py", line 68, in __init__
    raise Exception('site {!r} does not exist'.format(site_path))
Exception: site '/tmp/zoom/web/sites/192.168.0.100' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/zoom/zoom/middleware.py", line 300, in trap_errors
    return handler(request, *rest)
  File "/tmp/zoom/zoom/middleware.py", line 127, in serve_redirects
    result = handler(request, *rest)
  File "/tmp/zoom/zoom/middleware.py", line 214, in serve_favicon
    return handler(request, *rest)
  File "/tmp/zoom/zoom/middleware.py", line 171, in serve_static
    return handler(request, *rest)
  File "/tmp/zoom/zoom/middleware.py", line 192, in serve_images
    return handler(request, *rest)
  File "/tmp/zoom/zoom/middleware.py", line 224, in serve_html
    return handler(request, *rest)
  File "/tmp/zoom/zoom/middleware.py", line 348, in reset_modules
    return handler(request, *rest)
  File "/tmp/zoom/zoom/cookies.py", line 87, in cookie_handler
    response = handler(request, *rest)
  File "/tmp/zoom/zoom/middleware.py", line 270, in capture_stdout
    if isinstance(result.content, str) and '{*stdout*}' in result.content:
UnboundLocalError: local variable 'result' referenced before assignment

**Comment by hlainchb** [comment] 2017-04-22 00:56
Not able to reproduce this error and my understanding is that it's resolved so I'll close the issue.  Please let me know if you see it again.  Thanks for the report.

**Closed as completed by hlainchb** 2017-04-22 00:56 UTC
